project_id = "qwiklabs-gcp-00-37cfafcb9923"
vmname = "vminstance1"
machine_type = "n2-standard-2"
region = "us-central1"
zone = "us-central1-a"
image = "debian-cloud/debian-11"
vpcname = "vpc1"
subnetname = "subnet1"
ip_cidr_range = "10.2.0.0/16"
firewallname = "firewall1"
bqname = "sampledataset"
location ="US"
friendly_name ="test"
default_table_expiration_ms ="3600000"
table_id ="sampleid"
type = "DAY"


